source 'https://rubygems.org'

gem 'allure-cucumber'
gem 'cpf_faker', '1.3.0'
gem 'cucumber', '9.2.0'
gem 'faker', '1.8.5'
gem 'httparty', '0.22.0'
gem 'json_matchers'
gem 'nokogiri','1.15.6'
gem 'rspec', '3.7.0'
